version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    # command: "agent -dev -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0