server:
  port: 9001


spring:
  application:
    name: gateway-service
  config:
    import: optional:consul:localhost:8500
  data:
    mongodb:
      host: localhost
      port: 27017
      database: portfolio
      username: test
      password: test
      uri: mongodb://test:test@localhost:27017/admin?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      uuid-representation: standard

  webflux:
    base-path: /portfolio/gw/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.application.instance_id:${random.value}}
        health-check-path: /portfolio/gw/actuator/health
        health-check-interval: 50s
      config:
        enabled: true
        prefixes:
          - config/app/api/gatewaysecurity
          - config/infra/mongodb
          - config/infra/security
        format: KEY_VALUE
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: userservice
              uri: lb://userservice
              predicates:
                - Path= /api/v1/users/**
              filters:
                - StripPrefix=2
            - id: gateway-service
              uri: lb://gateway-service
              predicates:
                - Path= /api/v1/auth/**


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
auth:
  jwt:
    encoded-secret: bXktc3VwZXItc2VjdXJlLWp3dC1zZWNyZXQta2V5LTI1Ni1iaXQ=
    expiry-hour: 5
    cookie-name: gw-jwt-token